---
- hosts: localhost
  tasks:
    - name: add wheezy-backports repository and check if Debian version matches
      apt_repository: repo='deb http://ftp.de.debian.org/debian wheezy-backports main' state=present update_cache=yes
      when: ansible_distribution == 'Debian' and ansible_distribution_release == 'wheezy' and ansible_distribution_version == '7'
