---
- hosts: localhost
  vars:
    locale: en_US.UTF-8
    timezone: Europe/Sarajevo
    contents: "{{ lookup('file', '/etc/hosts.deny') }}"

  tasks:

    - name: server hostname is
      command: hostname

    - name: update cache on server
      apt: update_cache=yes

    - name: add wheezy backports repository
      apt_repository: repo='deb http://ftp.de.debian.org/debian wheezy-backports main' state=present

    - name: install basic packages
      tags:
      - basic
      - packages
      apt: name={{ item }} state=present
      with_items:
       - bsdutils
       - dialog
       - cron
       - man-db
       - nano
       - curl
       - locales

    - name: install basic utilities
      tags:
      - basic
      - utilities
      apt: name={{ item }} state=present
      with_items:
       - htop
       - ntp
       - ntpdate
    - name: Set timezone variables
      copy: content='{{ timezone }}'
            dest=/etc/timezone
            owner=root
            group=root
            mode=0644
            backup=yes
      notify:
        - update timezone
  handlers:
    - name: update timezone
      command: dpkg-reconfigure --frontend noninteractive tzdata

    - name: locale gen
      locale_gen: name=en_US.UTF-8 state=present

    - name: set locale
      command: /usr/sbin/update-locale LANG={{ locale }} LC_ALL=$locale

#     - debug: msg="the value of hosts.deny is {{ contents }}"
