---
- hosts: all
  remote_user: ansible
  sudo: yes
  vars:
    locale: en_US.UTF-8
    timezone: Europe/Sarajevo
  tasks:

    - name: locale gen
      locale_gen: name={{ locale }} state=present

    - name: set locale
      command: /usr/sbin/update-locale LANG={{ locale }} LC_ALL={{ locale }}
      notify:
        - update locales


    - name: Set timezone variables
      copy: content='{{ timezone }}'
            dest=/etc/timezone
            owner=root
            group=root
            mode=0644
            backup=yes
      notify:
        - update timezone

  handlers:
    - name: update timezone
      command: dpkg-reconfigure --frontend noninteractive tzdata
    - name: update locales
      command: dpkg-reconfigure --frontend noninteractive locales
